import type { Recipe } from "./types";

export const demoRecipes: Recipe[] = [
  {
    id: "demo-brisket",
    title: "Томлёная говяжья грудинка",
    summary: "Мягкая грудинка с дымной корочкой и долгим приготовлением на непрямом жаре.",
    category: "Говядина",
    grill_types: ["угольный", "камадо"],
    difficulty: "medium",
    servings_min: 6,
    servings_max: 8,
    prep_minutes: 30,
    cook_minutes: 420,
    rest_minutes: 45,
    equipment: ["Гриль с крышкой", "Термометр"],
    allergens: [],
    target_internal_temp_min_c: 92,
    target_internal_temp_max_c: 96,
    ingredients: [
      { name: "говяжья грудинка", quantity: 2.5, unit: "кг" },
      { name: "соль", quantity: 25, unit: "г" },
      { name: "перец чёрный", quantity: 18, unit: "г" },
    ],
    steps: [
      { instruction: "Удалите твёрдые участки жира, оставив равномерный слой около 5 мм." },
      { instruction: "Смешайте соль и перец, равномерно натрите грудинку со всех сторон." },
      { instruction: "Готовьте непрямым жаром при 120–130 °C до мягкости, затем дайте мясу отдохнуть." },
    ],
  },
  {
    id: "demo-chicken",
    title: "Курица с лимоном и травами",
    summary: "Целая курица с хрустящей кожей, чесноком, лимоном и ароматными травами.",
    category: "Птица",
    grill_types: ["угольный", "газовый"],
    difficulty: "easy",
    servings_min: 4,
    servings_max: 5,
    prep_minutes: 20,
    cook_minutes: 75,
    rest_minutes: 10,
    equipment: ["Гриль с крышкой", "Термометр"],
    allergens: [],
    target_internal_temp_min_c: 74,
    target_internal_temp_max_c: 76,
    ingredients: [
      { name: "курица", quantity: 1.6, unit: "кг" },
      { name: "лимон", quantity: 1, unit: "шт." },
      { name: "чеснок", quantity: 4, unit: "зубчика" },
    ],
    steps: [
      { instruction: "Обсушите курицу, смешайте чеснок, лимон и травы и натрите тушку." },
      { instruction: "Готовьте непрямым жаром до 74 °C в самой толстой части грудки." },
      { instruction: "Оставьте на 10 минут перед разделкой." },
    ],
  },
  {
    id: "demo-fish",
    title: "Лосось в медово-горчичной глазури",
    summary: "Сочный лосось с карамельной глазурью для быстрого ужина дома или на газовом гриле.",
    category: "Рыба и морепродукты",
    grill_types: ["дом", "духовка", "газовый"],
    difficulty: "easy",
    servings_min: 3,
    servings_max: 4,
    prep_minutes: 10,
    cook_minutes: 18,
    rest_minutes: 3,
    equipment: ["Духовка или гриль", "Кисть"],
    allergens: ["Рыба", "Горчица"],
    ingredients: [
      { name: "филе лосося", quantity: 700, unit: "г" },
      { name: "горчица", quantity: 2, unit: "ст. л." },
      { name: "мёд", quantity: 1, unit: "ст. л." },
    ],
    steps: [
      { instruction: "Смешайте горчицу с мёдом и тонким слоем нанесите на рыбу." },
      { instruction: "Запекайте или готовьте под крышкой до желаемой степени готовности." },
    ],
  },
  {
    id: "demo-vegetables",
    title: "Айсберг на гриле с кремовой заправкой",
    summary: "Подрумяненный салат айсберг с дымным ароматом и свежей сливочной заправкой.",
    category: "Овощи и гарниры",
    grill_types: ["угольный", "газовый"],
    difficulty: "easy",
    servings_min: 2,
    servings_max: 3,
    prep_minutes: 15,
    cook_minutes: 6,
    equipment: ["Решётка", "Щипцы"],
    allergens: ["Молоко"],
    ingredients: [
      { name: "салат айсберг", quantity: 1, unit: "кочан" },
      { name: "оливковое масло", quantity: 1, unit: "ст. л." },
      { name: "сметана", quantity: 100, unit: "г" },
    ],
    steps: [
      { instruction: "Разрежьте айсберг на четыре части, сохраняя кочерыжку." },
      { instruction: "Смажьте маслом и быстро обжарьте срезы над сильным жаром." },
      { instruction: "Полейте заправкой и подавайте сразу." },
    ],
  },
];
